package edu.sussex.tele.game.battle;

public enum BattlePhase {
	START_BATTLE, START_TURN, PLAYER_TARGETS, NPC_TARGETS, PLAYER_ATTACKS, NPC_ATTACKS, END_TURN, END_BATTLE, TARGET_DEAD, BATTLE_WON, BATTLE_LOST
}
